const productos = [
    {
        "id":1,
        "categoria":"Poleron",
        "title":"Poleron Amaranta",
        "description":"Poleron talla S, color Amaranta",
        "talla":"S",
        "color":"Amaranta",
        "stock":0,
        "price":20000,
        "ventas":1,
        "pictureUrl":"ModeloAmaranta.jpg"
    },
    {
        "id":2,
        "categoria":"Poleron",
        "title":"Poleron Amaranta",
        "description":"Poleron talla M, color Amaranta",
        "talla":"M",
        "color":"Amaranta",
        "stock":3,
        "price":22000,
        "ventas":10,
        "pictureUrl":"ModeloAmaranta.jpg"
    },
    {
        "id":3,
        "categoria":"Poleron",
        "title":"Poleron Amaranta",
        "description":"Poleron talla L, color Amaranta",
        "talla":"L",
        "color":"Amaranta",
        "stock":3,
        "price":23500,
        "ventas":2,
        "pictureUrl":"ModeloAmaranta.jpg"
    },
    {
        "id":4,
        "categoria":"Poleron",
        "title":"Poleron Amaranta",
        "description":"Poleron talla XL, color Amaranta",
        "talla":"XL",
        "color":"Amaranta",
        "stock":2,
        "price":25000,
        "ventas":2,
        "pictureUrl":"ModeloAmaranta.jpg"
    },
    {
        "id":5,
        "categoria":"Poleron",
        "title":"Poleron Amapola",
        "description":"Poleron talla S, color Amapola",
        "talla":"S",
        "color":"Amapola",
        "stock":2,
        "price":15000,
        "ventas":2,
        "pictureUrl":"ModeloAmapola.jpg"
    },
    {
        "id":6,
        "categoria":"Poleron",
        "title":"Poleron Amapola",
        "description":"Poleron talla M, color Amapola",
        "talla":"M",
        "color":"Amapola",
        "stock":3,
        "price":17500,
        "ventas":7,
        "pictureUrl":"ModeloAmapola.jpg"
    },
    {
        "id":7,
        "categoria":"Poleron",
        "title":"Poleron Amapola",
        "description":"Poleron talla L, color Amapola",
        "talla":"L",
        "color":"Amapola",
        "stock":0,
        "price":17500,
        "ventas":2,
        "pictureUrl":"ModeloAmapola.jpg"
    },
    {
        "id":8,
        "categoria":"Poleron",
        "title":"Poleron Amapola",
        "description":"Poleron talla XL, color Amapola",
        "talla":"XL",
        "color":"Amapola",
        "stock":2,
        "price":20000,
        "ventas":3,
        "pictureUrl":"ModeloAmapola.jpg"
    },
    {
        "id":9,
        "categoria":"Poleron",
        "title":"Poleron Jacinto",
        "description":"Poleron talla S, color Negro",
        "talla":"S",
        "color":"Negro",
        "stock":2,
        "price":10000,
        "ventas":1,
        "pictureUrl":"ModeloJacinto.jpg"
    },
    {
        "id":10,
        "categoria":"Poleron",
        "title":"Poleron Jacinto",
        "description":"Poleron talla M, color Negro",
        "talla":"M",
        "color":"Negro",
        "stock":0,
        "price":12500,
        "ventas":3,
        "pictureUrl":"ModeloJacinto.jpg"
    },
    {
        "id":11,
        "categoria":"Poleron",
        "title":"Poleron Jacinto",
        "description":"Poleron talla L, color Negro",
        "talla":"L",
        "color":"Negro",
        "stock":3,
        "price":13000,
        "ventas":2,
        "pictureUrl":"ModeloJacinto.jpg"
    },
    {
        "id":12,
        "categoria":"Poleron",
        "title":"Poleron Jacinto",
        "description":"Poleron talla XL, color Negro",
        "talla":"XL",
        "color":"Negro",
        "stock":2,
        "price":15000,
        "ventas":1,
        "pictureUrl":"ModeloJacinto.jpg"
    },
    {
        "id":13,
        "categoria":"Poleron",
        "title":"Poleron Jacinto",
        "description":"Poleron talla S, color Gris",
        "talla":"S",
        "color":"Gris",
        "stock":2,
        "price":10000,
        "ventas":1,
        "pictureUrl":"ModeloJacinto.jpg"
    },
    {
        "id":14,
        "categoria":"Poleron",
        "title":"Poleron Jacinto",
        "description":"Poleron talla M, color Gris",
        "talla":"M",
        "color":"Gris",
        "stock":0,
        "price":12500,
        "ventas":5,
        "pictureUrl":"ModeloJacinto.jpg"
    },
    {
        "id":15,
        "categoria":"Poleron",
        "title":"Poleron Jacinto",
        "description":"Poleron talla L, color Gris",
        "talla":"L",
        "color":"Gris",
        "stock":3,
        "price":13000,
        "ventas":3,
        "pictureUrl":"ModeloJacinto.jpg"
    },
    {
        "id":16,
        "categoria":"Poleron",
        "title":"Poleron Jacinto",
        "description":"Poleron talla XL, color Gris",
        "talla":"XL",
        "color":"Gris",
        "stock":2,
        "price":15000,
        "ventas":1,
        "pictureUrl":"ModeloJacinto.jpg"
    },
    {
        "id":17,
        "categoria":"Poleron",
        "title":"Poleron No me olvides",
        "description":"Poleron talla S, color Azul",
        "talla":"S",
        "color":"Azul",
        "stock":2,
        "price":17000,
        "ventas":1,
        "pictureUrl":"ModeloNomeolvides.jpg"
    },
    {
        "id":18,
        "categoria":"Poleron",
        "title":"Poleron No me olvides",
        "description":"Poleron talla M, color Azul",
        "talla":"M",
        "color":"Azul",
        "stock":3,
        "price":19000,
        "ventas":2,
        "pictureUrl":"ModeloNomeolvides.jpg"
    },
    {
        "id":19,
        "categoria":"Poleron",
        "title":"Poleron No me olvides",
        "description":"Poleron talla L, color Azul",
        "talla":"L",
        "color":"Azul",
        "stock":3,
        "price":19000,
        "ventas":4,
        "pictureUrl":"ModeloNomeolvides.jpg"
    },
    {
        "id":20,
        "categoria":"Poleron",
        "title":"Poleron No me olvides",
        "description":"Poleron talla XL, color Azul",
        "talla":"XL",
        "color":"Azul",
        "stock":2,
        "price":21000,
        "ventas":5,
        "pictureUrl":"ModeloNomeolvides.jpg"
    },
    {
        "id":21,
        "categoria":"Poleron",
        "title":"Poleron No me olvides",
        "description":"Poleron talla S, color Gris",
        "talla":"S",
        "color":"Gris",
        "stock":2,
        "price":17000,
        "ventas":2,
        "pictureUrl":"ModeloNomeolvides.jpg"
    },
    {
        "id":22,
        "categoria":"Poleron",
        "title":"Poleron No me olvides",
        "description":"Poleron talla M, color Gris",
        "talla":"M",
        "color":"Gris",
        "stock":3,
        "price":19000,
        "ventas":4,
        "pictureUrl":"ModeloNomeolvides.jpg"
    },
    {
        "id":23,
        "categoria":"Poleron",
        "title":"Poleron No me olvides",
        "description":"Poleron talla L, color Gris",
        "talla":"L",
        "color":"Gris",
        "stock":3,
        "price":19000,
        "ventas":3,
        "pictureUrl":"ModeloNomeolvides.jpg"
    },
    {
        "id":24,
        "categoria":"Poleron",
        "title":"Poleron No me olvides",
        "description":"Poleron talla XL, color Gris",
        "talla":"XL",
        "color":"Gris",
        "stock":2,
        "price":21000,
        "ventas":5,
        "pictureUrl":"ModeloNomeolvides.jpg"
    },
    {
        "id":25,
        "categoria":"Poleron",
        "title":"Poleron No me olvides",
        "description":"Poleron talla S, color Morado",
        "talla":"S",
        "color":"Morado",
        "stock":2,
        "price":17000,
        "ventas":2,
        "pictureUrl":"ModeloNomeolvides.jpg"
    },
    {
        "id":26,
        "categoria":"Poleron",
        "title":"Poleron No me olvides",
        "description":"Poleron talla M, color Morado",
        "talla":"M",
        "color":"Morado",
        "stock":3,
        "price":19000,
        "ventas":4,
        "pictureUrl":"ModeloNomeolvides.jpg"
    },
    {
        "id":27,
        "categoria":"Poleron",
        "title":"Poleron No me olvides",
        "description":"Poleron talla L, color Morado",
        "talla":"L",
        "color":"Morado",
        "stock":3,
        "price":19000,
        "ventas":3,
        "pictureUrl":"ModeloNomeolvides.jpg"
    },
    {
        "id":28,
        "categoria":"Poleron",
        "title":"Poleron No me olvides",
        "description":"Poleron talla XL, color Morado",
        "talla":"XL",
        "color":"Morado",
        "stock":2,
        "price":21000,
        "ventas":5,
        "pictureUrl":"ModeloNomeolvides.jpg"
    },
    {
        "id":29,
        "categoria":"Poleron",
        "title":"Poleron Violeta",
        "description":"Poleron talla S, color Violeta",
        "talla":"S",
        "color":"Violeta",
        "stock":2,
        "price":17500,
        "ventas":3,
        "pictureUrl":"ModeloVioleta.jpg"
    },
    {
        "id":30,
        "categoria":"Poleron",
        "title":"Poleron Violeta",
        "description":"Poleron talla M, color Violeta",
        "talla":"M",
        "color":"Violeta",
        "stock":3,
        "price":20000,
        "ventas":3,
        "pictureUrl":"ModeloVioleta.jpg"
    },
    {
        "id":31,
        "categoria":"Poleron",
        "title":"Poleron Violeta",
        "description":"Poleron talla L, color Violeta",
        "talla":"L",
        "color":"Violeta",
        "stock":3,
        "price":20000,
        "ventas":2,
        "pictureUrl":"ModeloVioleta.jpg"
    },
    {
        "id":32,
        "categoria":"Poleron",
        "title":"Poleron Violeta",
        "description":"Poleron talla XL, color Violeta",
        "talla":"XL",
        "color":"Violeta",
        "stock":2,
        "price":22500,
        "ventas":1,
        "pictureUrl":"ModeloVioleta.jpg"
    }
]

export default productos; 